config/routes.rb
Rails.application.routes.draw do
  resources :ecom_orders do
    post 'bulk_actions', on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ecom_orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ecom_order.rb
class EcomOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ecom_orders_controller.rb
class EcomOrdersController < ApplicationController
  before_action :set_ecom_order, only: %i[ show edit update destroy ]

  # GET /ecom_orders or /ecom_orders.json
  def index
    @ecom_orders = EcomOrder.all
  end

  # GET /ecom_orders/1 or /ecom_orders/1.json
  def show
  end

  # GET /ecom_orders/new
  def new
    @ecom_order = EcomOrder.new
  end

  # GET /ecom_orders/1/edit
  def edit
  end

  # POST /ecom_orders or /ecom_orders.json
  def create
    @ecom_order = EcomOrder.new(ecom_order_params)

    respond_to do |format|
      if @ecom_order.save
        format.html { redirect_to @ecom_order, notice: "Ecom order was successfully created." }
        format.json { render :show, status: :created, location: @ecom_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ecom_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ecom_orders/1 or /ecom_orders/1.json
  def update
    respond_to do |format|
      if @ecom_order.update(ecom_order_params)
        format.html { redirect_to @ecom_order, notice: "Ecom order was successfully updated." }
        format.json { render :show, status: :ok, location: @ecom_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ecom_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def bulk_actions
    redirect_to action: "index"
  end

  # DELETE /ecom_orders/1 or /ecom_orders/1.json
  def destroy
    @ecom_order.destroy
    respond_to do |format|
      format.html { redirect_to ecom_orders_url, notice: "Ecom order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ecom_order
      @ecom_order = EcomOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ecom_order_params
      params.require(:ecom_order).permit(:price, :item_sku, :purchase_date, :platform_order_num, :sales_channel, :status, :customer_name, :customer_state, :shipped_at, :num_items_shipped, :payment_method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ecom_orders_helper.rb
module EcomOrdersHelper
    def sales_channel_icon(ecom_order)
        icon_str = case ecom_order.sales_channel
        when /amazon/
            '<i class="fab fa-amazon"></i>'
        when /ebay/
            '<i class="fab fa-ebay"></i>'
        else
            '<i class="fas fa-question-circle"></i>'
        end

        icon_str.html_safe
    end

    def order_status_icon(ecom_order)
        icon_str = case ecom_order.status
        when /confirmed/
            '<i class="fas fa-money-bill-wave text-info"></i>'
        when /shipped/
            '<i class="fas fa-shipping-fast text-primary"></i>'
        when /delivered/
            '<i class="fas fa-truck-loading text-success"></i>'
        else
            '<i class="fas fa-question-circle"></i>'
        end

        icon_str.html_safe
    end
end

app/views/ecom_orders/_form.html.erb
<%= form_with(model: ecom_order, local: true) do |form| %>
  <% if ecom_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ecom_order.errors.count, "error") %> prohibited this ecom_order from being saved:</h2>

      <ul>
      <% ecom_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :item_sku %>
    <%= form.text_field :item_sku %>
  </div>

  <div class="field">
    <%= form.label :purchase_date %>
    <%= form.datetime_select :purchase_date %>
  </div>

  <div class="field">
    <%= form.label :platform_order_num %>
    <%= form.text_field :platform_order_num %>
  </div>

  <div class="field">
    <%= form.label :sales_channel %>
    <%= form.text_field :sales_channel %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="field">
    <%= form.label :customer_state %>
    <%= form.text_field :customer_state %>
  </div>

  <div class="field">
    <%= form.label :shipped_at %>
    <%= form.datetime_select :shipped_at %>
  </div>

  <div class="field">
    <%= form.label :num_items_shipped %>
    <%= form.number_field :num_items_shipped %>
  </div>

  <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ecom_orders/edit.html.erb
<h1>Editing Ecom Order</h1>

<%= render 'form', ecom_order: @ecom_order %>

<%= link_to 'Show', @ecom_order %> |
<%= link_to 'Back', ecom_orders_path %>

app/views/ecom_orders/index.html.erb
<link type="text/css" href="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.12/css/dataTables.checkboxes.css" rel="stylesheet" />
<p id="notice"><%= notice %></p>
<h1>Ecom Orders</h1>
<table id='ordersTable' class='table table-striped table-sm'>
  <thead>
    <tr>
      <th>
        <div class='btn-group'>
          <button type='button' class='btn btn-light btn-sm'><span id='selectAll'><i class="far fa-square"></i></span></button>
          <button type="button" class="btn btn-light btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu">
            <a id='numSelectedText' class='dropdown-item' href='#'>(0) Orders Selected</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item bulkActionLink" href="#" data-action='refund'>Refund</a>
            <a class="dropdown-item bulkActionLink" href="#" data-action='email'>Send Email</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item bulkActionLink" href="#" data-action='question'>Question Sanity</a>
            <a class="dropdown-item bulkActionLink" href="#" data-action='stalk'>Stalk online</a>
          </div>
        </div>
      </th>
      <th></th>
      <th>Purchase date</th>
      <th>Purchase</th>
      <th>Price</th>
      <th>Status</th>
      <th>Customer</th>
      <th>Shipped at</th>
      <th>Num items shipped</th>
      <th>Payment method</th>
    </tr>
  </thead>
  <tbody>
    <% @ecom_orders.each do |ecom_order| %>
      <tr>
        <td><%= ecom_order.id %></td>
        <td><%= sales_channel_icon(ecom_order) %></td>
        <td><%= local_time ecom_order.purchase_date, '%B %e, %Y %l:%M%P %Z' %></td>
        <td><%= ecom_order.platform_order_num %><br/>
          <strong>SKU: </strong><%= link_to ecom_order.item_sku, "#" %>
        </td>
        <td><%= ecom_order.price %></td>
        <td><%= order_status_icon(ecom_order) %></td>
        <td><%= ecom_order.customer_name %><br/>
          <%= ecom_order.customer_state %></td>
        <td><%= local_time(ecom_order.shipped_at, '%B %e, %Y %l:%M%P %Z') if ecom_order.shipped_at %></td>
        <td><%= ecom_order.num_items_shipped %></td>
        <td><%= ecom_order.payment_method %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= simple_form_for(EcomOrder.new, url: bulk_actions_ecom_orders_path, html: { id: 'bulkActionsForm', class: 'mt-4 border-top pt-2'}) do |f| %>
  <input type="hidden" id="formActionType" name="action_type" value="">
<% end %>

<script type="text/javascript" src="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.12/js/dataTables.checkboxes.min.js"></script>

<script>
  $(document).ready(function() {
    var oTable = $("#ordersTable ").DataTable({
      order: [[2, 'desc']],   // order by 3rd column ( 2nd index = Purchase date)
      columnDefs: [
        {
          targets: 0,
          checkboxes: {
            selectRow: true,
            selectAll: false
          }
        }
      ],
      select: {
        style: 'multi'
      }
    });

  		$('#selectAll').on('click', function(params) {
  			var rows_selected = oTable.column(0).checkboxes.selected();

  			if (rows_selected.length == oTable.page.len()) {
  				oTable.column(0).checkboxes.select(false);
  			} else {
  				oTable.column(0).checkboxes.select(true);
  			}
  		})

   		$('.bulkActionLink').on('click', function(params) {
  			// console.log(this.dataset.action)
  			var rows_selected = oTable.column(0).checkboxes.selected();

  			if (rows_selected.length > 0) {
  				$("#formActionType").val(this.dataset.action);
  				$("#bulkActionsForm").submit();
  			}
  		})

  	// do something with all selected rows
  		$('#bulkActionsForm').on('submit', function(e){
  			var form = this;

  			var rows_selected = oTable.column(0).checkboxes.selected();

  			// Iterate over all selected checkboxes
  			$.each(rows_selected, function(index, rowId){
  				// Create a hidden element
  				$(form).append(
  					$('<input>')
  					.attr('type', 'hidden')
  					.attr('name', 'id[]')
  					.val(rowId)
  				);
  			});
  		});


  });
</script>

app/views/ecom_orders/new.html.erb
<h1>New Ecom Order</h1>

<%= render 'form', ecom_order: @ecom_order %>

<%= link_to 'Back', ecom_orders_path %>

app/views/ecom_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @ecom_order.price %>
</p>

<p>
  <strong>Item sku:</strong>
  <%= @ecom_order.item_sku %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @ecom_order.purchase_date %>
</p>

<p>
  <strong>Platform order num:</strong>
  <%= @ecom_order.platform_order_num %>
</p>

<p>
  <strong>Sales channel:</strong>
  <%= @ecom_order.sales_channel %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ecom_order.status %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @ecom_order.customer_name %>
</p>

<p>
  <strong>Customer state:</strong>
  <%= @ecom_order.customer_state %>
</p>

<p>
  <strong>Shipped at:</strong>
  <%= @ecom_order.shipped_at %>
</p>

<p>
  <strong>Num items shipped:</strong>
  <%= @ecom_order.num_items_shipped %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @ecom_order.payment_method %>
</p>

<%= link_to 'Edit', edit_ecom_order_path(@ecom_order) %> |
<%= link_to 'Back', ecom_orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datatablesdemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='container-fluid'>
    <%= yield %>
    </div>
  </body>
</html>